-- SQLBook: Code
CREATE TABLE role (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE user (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    siret VARCHAR(100) NULL,
    FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE category (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE video (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    title VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    upload_date DATE NOT NULL,
    duration INT,
    video_url  VARCHAR(255) NOT NULL,
    img_url VARCHAR(255),
    access VARCHAR(100) NOT NULL,
    category_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE tag (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL UNIQUE,
    category_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE video_tag (
    tag_id INT UNSIGNED NOT NULL,
    video_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (video_id) REFERENCES video(id),
    FOREIGN KEY (tag_id) REFERENCES tag(id)
);